//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesBalance
    {
        public int ID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
