//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ProductOrders = new HashSet<ProductOrder>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> ShipmentPrice { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public string Notes { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> ShipmentCompanyID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> SellerID { get; set; }
        public string PageID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Seller { get; set; }
        public virtual ShipmentCompany ShipmentCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}
