//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<double> OrginalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<long> ColorID { get; set; }
        public Nullable<long> SizeID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
