//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> From { get; set; }
        public Nullable<double> To { get; set; }
        public string RateColor { get; set; }
    }
}
