//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetView
    {
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string EmpName { get; set; }
        public string EmpMobileNumber1 { get; set; }
        public string EmpMobileNumber2 { get; set; }
        public Nullable<double> ShipmentPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public System.DateTime DisplayDate { get; set; }
    }
}
