//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> NumberOfPieces { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<long> TodayTransactionID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual TodayTransaction TodayTransaction { get; set; }
    }
}
