//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesShop.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClothesShop.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sales Rate.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Approve.
        /// </summary>
        public static string AddAndApprove {
            get {
                return ResourceManager.GetString("AddAndApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Balance.
        /// </summary>
        public static string AddBalance {
            get {
                return ResourceManager.GetString("AddBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Color.
        /// </summary>
        public static string AddColor {
            get {
                return ResourceManager.GetString("AddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expenses.
        /// </summary>
        public static string AddExpenses {
            get {
                return ResourceManager.GetString("AddExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Login.
        /// </summary>
        public static string AddLogin {
            get {
                return ResourceManager.GetString("AddLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Order.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Orders.
        /// </summary>
        public static string AddOrders {
            get {
                return ResourceManager.GetString("AddOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Supplier.
        /// </summary>
        public static string AddProductSupplier {
            get {
                return ResourceManager.GetString("AddProductSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shipment Company.
        /// </summary>
        public static string AddShipmentCompany {
            get {
                return ResourceManager.GetString("AddShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Size.
        /// </summary>
        public static string AddSize {
            get {
                return ResourceManager.GetString("AddSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transaction.
        /// </summary>
        public static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationName.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Delete Color?.
        /// </summary>
        public static string AreYouSureDeleteColor {
            get {
                return ResourceManager.GetString("AreYouSureDeleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Employee?.
        /// </summary>
        public static string AreYouSureDeleteEmployee {
            get {
                return ResourceManager.GetString("AreYouSureDeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete login?.
        /// </summary>
        public static string AreYouSureDeleteLogin {
            get {
                return ResourceManager.GetString("AreYouSureDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete order?.
        /// </summary>
        public static string AreYouSureDeleteOrder {
            get {
                return ResourceManager.GetString("AreYouSureDeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete order from current delivery man and change status of order to be new?.
        /// </summary>
        public static string AreYouSureDeleteOrderFromDeliveryMan {
            get {
                return ResourceManager.GetString("AreYouSureDeleteOrderFromDeliveryMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete product?.
        /// </summary>
        public static string AreYouSureDeleteProduct {
            get {
                return ResourceManager.GetString("AreYouSureDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Product Supplier.
        /// </summary>
        public static string AreYouSureDeleteProductSupplier {
            get {
                return ResourceManager.GetString("AreYouSureDeleteProductSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete sales rate?.
        /// </summary>
        public static string AreYouSureDeleteSalesRate {
            get {
                return ResourceManager.GetString("AreYouSureDeleteSalesRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Shipment company?.
        /// </summary>
        public static string AreYouSureDeleteShipmentCompany {
            get {
                return ResourceManager.GetString("AreYouSureDeleteShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete size?.
        /// </summary>
        public static string AreYouSureDeleteSize {
            get {
                return ResourceManager.GetString("AreYouSureDeleteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Delete Supplier?.
        /// </summary>
        public static string AreYouSureDeleteSupplier {
            get {
                return ResourceManager.GetString("AreYouSureDeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Delete This Process?.
        /// </summary>
        public static string AreYouSureDeleteThisProcess {
            get {
                return ResourceManager.GetString("AreYouSureDeleteThisProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete today expense?.
        /// </summary>
        public static string AreYouSureDeleteTodayExpense {
            get {
                return ResourceManager.GetString("AreYouSureDeleteTodayExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete today sales?.
        /// </summary>
        public static string AreYouSureDeleteTodaySales {
            get {
                return ResourceManager.GetString("AreYouSureDeleteTodaySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete All Data.
        /// </summary>
        public static string AreYouSureToDeleteAllData {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Change Orders Status to.
        /// </summary>
        public static string AreYouSureYouWantToChangeOrdersStatusTo {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToChangeOrdersStatusTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Change Status To.
        /// </summary>
        public static string AreYouSureYouWantToChangeStatusTo {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToChangeStatusTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string AvailableBalance {
            get {
                return ResourceManager.GetString("AvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Licence Picture.
        /// </summary>
        public static string BackLicencePicture {
            get {
                return ResourceManager.GetString("BackLicencePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back SSN Picture.
        /// </summary>
        public static string BackSSNPicture {
            get {
                return ResourceManager.GetString("BackSSNPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Details.
        /// </summary>
        public static string BalanceDetails {
            get {
                return ResourceManager.GetString("BalanceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled By Agent.
        /// </summary>
        public static string CanceledByAgent {
            get {
                return ResourceManager.GetString("CanceledByAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, number of days must be less than or equal {0} days.
        /// </summary>
        public static string CannotExccedDays {
            get {
                return ResourceManager.GetString("CannotExccedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Orders Status.
        /// </summary>
        public static string ChangeOrdersStatus {
            get {
                return ResourceManager.GetString("ChangeOrdersStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Order Status.
        /// </summary>
        public static string ChangeOrderStatus {
            get {
                return ResourceManager.GetString("ChangeOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorAlreadyLinkedWithProduct.
        /// </summary>
        public static string ColorAlreadyLinkedWithProduct {
            get {
                return ResourceManager.GetString("ColorAlreadyLinkedWithProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        public static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        public static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete System Data.
        /// </summary>
        public static string DeleteSystemData {
            get {
                return ResourceManager.GetString("DeleteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Man.
        /// </summary>
        public static string DeliveryMan {
            get {
                return ResourceManager.GetString("DeliveryMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Balance.
        /// </summary>
        public static string EditBalance {
            get {
                return ResourceManager.GetString("EditBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Color.
        /// </summary>
        public static string EditColor {
            get {
                return ResourceManager.GetString("EditColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Successfully.
        /// </summary>
        public static string EditedSuccessfully {
            get {
                return ResourceManager.GetString("EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expenses.
        /// </summary>
        public static string EditExpenses {
            get {
                return ResourceManager.GetString("EditExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        public static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Orders.
        /// </summary>
        public static string EditOrders {
            get {
                return ResourceManager.GetString("EditOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Supplier.
        /// </summary>
        public static string EditProductSupplier {
            get {
                return ResourceManager.GetString("EditProductSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transaction.
        /// </summary>
        public static string EditTransaction {
            get {
                return ResourceManager.GetString("EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elba4a.
        /// </summary>
        public static string Elba4a {
            get {
                return ResourceManager.GetString("Elba4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Statistics.
        /// </summary>
        public static string EmployeesStatistics {
            get {
                return ResourceManager.GetString("EmployeesStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be equal {2} characters long..
        /// </summary>
        public static string EqualText {
            get {
                return ResourceManager.GetString("EqualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Deleting.
        /// </summary>
        public static string ErrorWhileDeleting {
            get {
                return ResourceManager.GetString("ErrorWhileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Login.
        /// </summary>
        public static string ErrorWhileLogin {
            get {
                return ResourceManager.GetString("ErrorWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string ErrorWhileProcessRequest {
            get {
                return ResourceManager.GetString("ErrorWhileProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel sheet.
        /// </summary>
        public static string ExcelSheet {
            get {
                return ResourceManager.GetString("ExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Licence Picture.
        /// </summary>
        public static string FrontLicencePicture {
            get {
                return ResourceManager.GetString("FrontLicencePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front SSN Picture.
        /// </summary>
        public static string FrontSSNPicture {
            get {
                return ResourceManager.GetString("FrontSSNPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server eerror please contact your administrator.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Paid Amount.
        /// </summary>
        public static string InvalidPaidAmount {
            get {
                return ResourceManager.GetString("InvalidPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SSN.
        /// </summary>
        public static string InvalidSSN {
            get {
                return ResourceManager.GetString("InvalidSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserName Or Password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.E.
        /// </summary>
        public static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossses.
        /// </summary>
        public static string Lossses {
            get {
                return ResourceManager.GetString("Lossses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number 1.
        /// </summary>
        public static string MobileNumber1 {
            get {
                return ResourceManager.GetString("MobileNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number 2.
        /// </summary>
        public static string MobileNumber2 {
            get {
                return ResourceManager.GetString("MobileNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Transactions.
        /// </summary>
        public static string MoneyTransactions {
            get {
                return ResourceManager.GetString("MoneyTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Statistics.
        /// </summary>
        public static string MonthlyStatistics {
            get {
                return ResourceManager.GetString("MonthlyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than {1}..
        /// </summary>
        public static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be less than or equal to {1} character..
        /// </summary>
        public static string MustBeLessThan {
            get {
                return ResourceManager.GetString("MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Expenses must have at least one expen info.
        /// </summary>
        public static string MustHaveExpenses {
            get {
                return ResourceManager.GetString("MustHaveExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products must be greater than or equal 1.
        /// </summary>
        public static string MustHaveProducts {
            get {
                return ResourceManager.GetString("MustHaveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today sales must have at least one sale info.
        /// </summary>
        public static string MustHaveSales {
            get {
                return ResourceManager.GetString("MustHaveSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no orders has been added to the current delivery man.
        /// </summary>
        public static string NoAddedOrders {
            get {
                return ResourceManager.GetString("NoAddedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoColors.
        /// </summary>
        public static string NoColors {
            get {
                return ResourceManager.GetString("NoColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delivery Man.
        /// </summary>
        public static string NoDeliveryMan {
            get {
                return ResourceManager.GetString("NoDeliveryMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employees.
        /// </summary>
        public static string NoEmployees {
            get {
                return ResourceManager.GetString("NoEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notes.
        /// </summary>
        public static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Products.
        /// </summary>
        public static string NoProducts {
            get {
                return ResourceManager.GetString("NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Seller.
        /// </summary>
        public static string NoSeller {
            get {
                return ResourceManager.GetString("NoSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shipment Companies.
        /// </summary>
        public static string NoShipmentCompanys {
            get {
                return ResourceManager.GetString("NoShipmentCompanys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sizes.
        /// </summary>
        public static string NoSizes {
            get {
                return ResourceManager.GetString("NoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Suppliers.
        /// </summary>
        public static string NoSuppliers {
            get {
                return ResourceManager.GetString("NoSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Delivered.
        /// </summary>
        public static string NotDelivered {
            get {
                return ResourceManager.GetString("NotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Orders.
        /// </summary>
        public static string NumberOfOrders {
            get {
                return ResourceManager.GetString("NumberOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pieces.
        /// </summary>
        public static string NumberOfPieces {
            get {
                return ResourceManager.GetString("NumberOfPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contains numbers only.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Delivery.
        /// </summary>
        public static string OrdersDelivery {
            get {
                return ResourceManager.GetString("OrdersDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Statistics.
        /// </summary>
        public static string OrdersStatistics {
            get {
                return ResourceManager.GetString("OrdersStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Status.
        /// </summary>
        public static string OrdersStatus {
            get {
                return ResourceManager.GetString("OrdersStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price.
        /// </summary>
        public static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Info.
        /// </summary>
        public static string OtherInfo {
            get {
                return ResourceManager.GetString("OtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} Of {1} ({2}).
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you requested is not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partialy Delivered.
        /// </summary>
        public static string PartialyDelivered {
            get {
                return ResourceManager.GetString("PartialyDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password And Confirm Not Matched.
        /// </summary>
        public static string PasswordAndConfirmNotMatched {
            get {
                return ResourceManager.GetString("PasswordAndConfirmNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Average.
        /// </summary>
        public static string PaymentAverage {
            get {
                return ResourceManager.GetString("PaymentAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Rate.
        /// </summary>
        public static string PaymentRate {
            get {
                return ResourceManager.GetString("PaymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece Price.
        /// </summary>
        public static string PiecePrice {
            get {
                return ResourceManager.GetString("PiecePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Sheet.
        /// </summary>
        public static string PrintSheet {
            get {
                return ResourceManager.GetString("PrintSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Summary.
        /// </summary>
        public static string ProductSummary {
            get {
                return ResourceManager.GetString("ProductSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Suppliers.
        /// </summary>
        public static string ProductSuppliers {
            get {
                return ResourceManager.GetString("ProductSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is Required Field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rate.
        /// </summary>
        public static string SalesRate {
            get {
                return ResourceManager.GetString("SalesRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select At Least One Order.
        /// </summary>
        public static string SelectAtLeastOneOrder {
            get {
                return ResourceManager.GetString("SelectAtLeastOneOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        public static string SellingPrice {
            get {
                return ResourceManager.GetString("SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Companies.
        /// </summary>
        public static string ShipmentCompanies {
            get {
                return ResourceManager.GetString("ShipmentCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Company.
        /// </summary>
        public static string ShipmentCompany {
            get {
                return ResourceManager.GetString("ShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Price.
        /// </summary>
        public static string ShipmentPrice {
            get {
                return ResourceManager.GetString("ShipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string ShowingRecords {
            get {
                return ResourceManager.GetString("ShowingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Working Date.
        /// </summary>
        public static string StartWorkingDate {
            get {
                return ResourceManager.GetString("StartWorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics And Balance.
        /// </summary>
        public static string StatisticsAndBalance {
            get {
                return ResourceManager.GetString("StatisticsAndBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Details.
        /// </summary>
        public static string StatisticsDetails {
            get {
                return ResourceManager.GetString("StatisticsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing Records.
        /// </summary>
        public static string StoringRecords {
            get {
                return ResourceManager.GetString("StoringRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Expenses.
        /// </summary>
        public static string TodayExpenses {
            get {
                return ResourceManager.GetString("TodayExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Sales.
        /// </summary>
        public static string TodaySales {
            get {
                return ResourceManager.GetString("TodaySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Summary.
        /// </summary>
        public static string TodaySummary {
            get {
                return ResourceManager.GetString("TodaySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Transactions.
        /// </summary>
        public static string TodayTransactions {
            get {
                return ResourceManager.GetString("TodayTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance.
        /// </summary>
        public static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deduction.
        /// </summary>
        public static string TotalDeduction {
            get {
                return ResourceManager.GetString("TotalDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expenses.
        /// </summary>
        public static string TotalExpenses {
            get {
                return ResourceManager.GetString("TotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Incoming.
        /// </summary>
        public static string TotalIncoming {
            get {
                return ResourceManager.GetString("TotalIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally Delivered.
        /// </summary>
        public static string TotallyDelivered {
            get {
                return ResourceManager.GetString("TotallyDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number Of Pieces.
        /// </summary>
        public static string TotalNumberOfPieces {
            get {
                return ResourceManager.GetString("TotalNumberOfPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Orders Count.
        /// </summary>
        public static string TotalOrders {
            get {
                return ResourceManager.GetString("TotalOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Orders Cash.
        /// </summary>
        public static string TotalOrdersCash {
            get {
                return ResourceManager.GetString("TotalOrdersCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product Price.
        /// </summary>
        public static string TotalProductPrice {
            get {
                return ResourceManager.GetString("TotalProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining.
        /// </summary>
        public static string TotalRemaining {
            get {
                return ResourceManager.GetString("TotalRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Returned.
        /// </summary>
        public static string TotalReturned {
            get {
                return ResourceManager.GetString("TotalReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reward.
        /// </summary>
        public static string TotalReward {
            get {
                return ResourceManager.GetString("TotalReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Selled.
        /// </summary>
        public static string TotalSelled {
            get {
                return ResourceManager.GetString("TotalSelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Selling Price.
        /// </summary>
        public static string TotalSellingPrice {
            get {
                return ResourceManager.GetString("TotalSellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Withdraw.
        /// </summary>
        public static string TotalWithdraw {
            get {
                return ResourceManager.GetString("TotalWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorized to perform this action.
        /// </summary>
        public static string UnAuthorized {
            get {
                return ResourceManager.GetString("UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Color.
        /// </summary>
        public static string UpdateColor {
            get {
                return ResourceManager.GetString("UpdateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Employee.
        /// </summary>
        public static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Login.
        /// </summary>
        public static string UpdateLogin {
            get {
                return ResourceManager.GetString("UpdateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product.
        /// </summary>
        public static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Rights.
        /// </summary>
        public static string UpdateRights {
            get {
                return ResourceManager.GetString("UpdateRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shipment Company.
        /// </summary>
        public static string UpdateShipmentCompany {
            get {
                return ResourceManager.GetString("UpdateShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Size.
        /// </summary>
        public static string UpdateSize {
            get {
                return ResourceManager.GetString("UpdateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Supplier.
        /// </summary>
        public static string UpdateSupplier {
            get {
                return ResourceManager.GetString("UpdateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Already Exists.
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Statistics.
        /// </summary>
        public static string WeeklyStatistics {
            get {
                return ResourceManager.GetString("WeeklyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Summary.
        /// </summary>
        public static string WeekSummary {
            get {
                return ResourceManager.GetString("WeekSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Shipment Company.
        /// </summary>
        public static string WithoutShipmentCompany {
            get {
                return ResourceManager.GetString("WithoutShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Information.
        /// </summary>
        public static string WorkInformation {
            get {
                return ResourceManager.GetString("WorkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
